site_name: Camada Física da Computação - Insper
site_url: https://insper.github.io/camadafisica/
theme:
  name: active-handout-theme
  locale: pt_BR

INHERIT: active-handout.yml


extra:
  custom_variables:
    repo_aps: https://github.com/insper/camadafisica
    repo_aps_git: https://github.com/insper/camadafisica.git

extra_javascript:
  - js/tabs.js
  - js/termynal.js
  - js/custom.js

extra_css:
    - css/termynal.css
    - css/equipe.css

# Extensions / plugins
plugins:
  - mkdocs-jupyter:
      execute: False

nav:
  - Home: index.md
  - deadlines.md
  - Instalação: infra.md
  - Projeto 0 - Base Python:
    - Introdução: classes/projeto0/teoria.md
    - Atividade Python: classes/projeto0/atividade-aula1.ipynb
  - Projeto 1 - Loopback:
    - Introdução: classes/projeto1/intro.md
    - Enunciado: classes/projeto1/enunciado.md
  # - Projeto 2 - Ponto Flutuante:
  #   - Introdução: classes/projeto2/intro.md
  #   - Enunciado: classes/projeto2/enunciado.md
  # - Projeto 3 - Datagrama:
  #   - Introdução: classes/projeto3/intro.md
  #   - Enunciado: classes/projeto3/enunciado.md
  # - Projeto 4 - Checksum:
  #   - Introdução: classes/projeto4/intro.md
  #   - Enunciado: classes/projeto4/enunciado.md
  # - Projeto 5 - Serialização:
  #   - Introdução: classes/projeto5/intro.md
  #   - Enunciado: classes/projeto5/enunciado.md
  #   - Projeto 6:
  #   - classes/projeto6/intro.md
  #   - classes/projeto6/enunciado.md
  # - Projeto 7:
  #   - classes/projeto7/intro.md
  #   - classes/projeto7/enunciado.md
  # - "Projeto 8 - modulação AM":
  #   - classes/projeto8/intro.md
  #   - classes/projeto8/enunciado.md
  # - "Projeto 9":
  #   - classes/projeto9/intro.md
  #   - classes/projeto9/enunciado.md
  #   - "Projeto extra":
  #   - classes/02-api/api_deploy.md




 