site_name: Camada Física da Computação - Insper
site_url: https://insper.github.io/camadafisica/
theme:
  name: active-handout-theme
  locale: pt_BR

INHERIT: active-handout.yml


extra:
  custom_variables:
    repo_aps: https://github.com/insper/camadafisica
    repo_aps_git: https://github.com/insper/camadafisica.git

extra_javascript:
  - js/tabs.js
  - js/termynal.js
  - js/custom.js

extra_css:
    - css/termynal.css
    - css/equipe.css

nav:
  - 'Home': index.md
  - deadlines.md
  - contributions.md
  - Classes:
    - "Projeto 1":
      - classes/01-projeto/intro.md
      - classes/01-projeto/enunciado.md
    - "Projeto 2":
      - classes/02-api/api_deploy.md
    - "Projeto 3":
      - classes/03-batch/intro.md
      - classes/03-batch/data_formats.md
    - "Projeto 4":
      - classes/04-int01/faq.md
      - classes/04-int01/int01.md
 



 